config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :bookcodes

  resources :people
  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :bookcode
  belongs_to :buyer
  belongs_to :seller
end

app/models/bookcode.rb
class Bookcode < ActiveRecord::Base
  has_many :books
end

app/models/buyer.rb
class Buyer < Person
  has_many :books
end

app/models/person.rb
class Person < ActiveRecord::Base
  
end

app/models/seller.rb
class Seller < Person
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookcodes_controller.rb
class BookcodesController < ApplicationController
  before_action :set_bookcode, only: [:show, :edit, :update, :destroy]

  # GET /bookcodes
  # GET /bookcodes.json
  def index
    @bookcodes = Bookcode.all
  end

  # GET /bookcodes/1
  # GET /bookcodes/1.json
  def show
  end

  # GET /bookcodes/new
  def new
    @bookcode = Bookcode.new
  end

  # GET /bookcodes/1/edit
  def edit
  end

  # POST /bookcodes
  # POST /bookcodes.json
  def create
    @bookcode = Bookcode.new(bookcode_params)

    respond_to do |format|
      if @bookcode.save
        format.html { redirect_to @bookcode, notice: 'Bookcode was successfully created.' }
        format.json { render :show, status: :created, location: @bookcode }
      else
        format.html { render :new }
        format.json { render json: @bookcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookcodes/1
  # PATCH/PUT /bookcodes/1.json
  def update
    respond_to do |format|
      if @bookcode.update(bookcode_params)
        format.html { redirect_to @bookcode, notice: 'Bookcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookcode }
      else
        format.html { render :edit }
        format.json { render json: @bookcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookcodes/1
  # DELETE /bookcodes/1.json
  def destroy
    @bookcode.destroy
    respond_to do |format|
      format.html { redirect_to bookcodes_url, notice: 'Bookcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookcode
      @bookcode = Bookcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookcode_params
      params.require(:bookcode).permit(:name, :price, :isbn)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:seller_id, :bookcode_id, :buyer_id, :seller_id, :seller_price, :last_price, :send_flag)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookcodes_helper.rb
module BookcodesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/bookcodes/_form.html.erb
<%= form_for(@bookcode) do |f| %>
  <% if @bookcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookcode.errors.count, "error") %> prohibited this bookcode from being saved:</h2>

      <ul>
      <% @bookcode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookcodes/edit.html.erb
<h1>Editing bookcode</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookcode %> |
<%= link_to 'Back', bookcodes_path %>

app/views/bookcodes/index.html.erb
<h1>Bookcodes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Isbn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookcodes.each do |bookcode| %>
      <tr>
        <td><%= bookcode.name %></td>
        <td><%= bookcode.price %></td>
        <td><%= bookcode.isbn %></td>
        <td><%= link_to 'Show', bookcode %></td>
        <td><%= link_to 'Edit', edit_bookcode_path(bookcode) %></td>
        <td><%= link_to 'Destroy', bookcode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookcode', new_bookcode_path %>

app/views/bookcodes/new.html.erb
<h1>New bookcode</h1>

<%= render 'form' %>

<%= link_to 'Back', bookcodes_path %>

app/views/bookcodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bookcode.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bookcode.price %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @bookcode.isbn %>
</p>

<%= link_to 'Edit', edit_bookcode_path(@bookcode) %> |
<%= link_to 'Back', bookcodes_path %>

app/views/books/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Simple Form</div>
      <div class="panel-body">
        <%= simple_form_for @book, wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
          <%= f.input :seller_id %><br>
          <%= f.input :bookcode_id %><br>
          <%= f.input :buyer_id %><br>
          <%= f.input :seller_price %><br>
          <%= f.input :last_price %><br>
          <%= f.input :send_flag %><br>
          <%= f.button :submit  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book, class: "btn btn-link" %> |
<%= link_to 'Back', books_path, class: "btn btn-link" %>

app/views/books/index.html.erb
<h1>Books</h1>

<table class="table">
  <thead>
    <tr>
      <th>Seller</th>
      <th>Bookcode</th>
      <th>Buyer</th>
      <th>Seller price</th>
      <th>Last price</th>
      <th>Send flag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.seller_id %></td>
        <td><%= book.bookcode_id %></td>
        <td><%= book.buyer_id %></td>
        <td><%= book.seller_price %></td>
        <td><%= book.last_price %></td>
        <td><%= book.send_flag %></td>
        <td><%= link_to 'Show', book, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_book_path(book), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path, class: "btn btn-link" %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path, class: "btn btn-link" %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seller:</strong>
  <%= link_to @book.seller.name, person_path(@book.seller) %>
</p>

<p>
  <strong>Book:</strong>
  <ul>
    <li>name: <%= @book.bookcode.name %></li>
    <li>price: <%= @book.bookcode.price %></li>
    <li>isbn: <%= @book.bookcode.isbn %></li>
  </ul>
</p>

<p>
  <strong>Buyer:</strong>
  <%= link_to @book.buyer.name, person_path(@book.buyer) %>
</p>

<p>
  <strong>Seller price:</strong>
  <%= @book.seller_price %>
</p>

<p>
  <strong>Last price:</strong>
  <%= @book.last_price %>
</p>

<p>
  <strong>Send flag:</strong>
  <%= @book.send_flag %>
</p>

<%= link_to 'Edit', edit_book_path(@book), class: "btn btn-link" %> |
<%= link_to 'Back', books_path, class: "btn btn-link" %>

app/views/layouts/_header.html.erb
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Ink-You</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><%= link_to 'books', books_path %></li>
              <li><%= link_to 'bookcodes', bookcodes_path %></li>
              <li><%= link_to 'people', people_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
              <li><a href="../navbar-static-top/">Static top</a></li>
              <li><a href="../navbar-fixed-top/">Fixed top</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InkYou</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="jumbotron">
  <div class="container">
    <%= yield %>
  </div>
  </div>
</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>People</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= link_to 'Show', person_path(person) %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person_path(person), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Books to <%= @person.type == "seller" ? "sell:" : "buy:" %></strong>
  <% @person.books.each do |book| %>
    <%= link_to book.bookcode.name, book_path(book) %><br>
  <% end %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>